title:            lvwzhen
description:      just a Blog
url:              # Site url.
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          lvwzhen # Your name.
disqus_shortname: lvwzhengithub # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.

links:
  - name:         Home
    url:          http://lvwzhen.github.io
  - name:         Feed
    url:          /feed.xml
  - name:         Thus.in
    url:          http://thus.in
    external:     true
  - name:         Email
    url:          mailto:lvwzhen@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/lvwzhen
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
